### ISSUE TITLE
Add Demo Image for better reliability 

### ISSUE THREAD

**Issue by HomeDev68** [UlyssesZh/grs-action#1]
Add a Demo Image of the generated stats for better reliability.

**Comment by UlyssesZh** [comment]
Could you clarify why is a demo image related to reliability? I think people should refer to anuraghazra/github-readme-stats for images.

**Comment by HomeDev68** [comment]
A demo of how this action works and the result it produces

**Comment by UlyssesZh** [comment]
There already is: https://github.com/UlyssesZh/grs-action/tree/gh-action-output

**Comment by HomeDev68** [comment]
Put in the README for a quick demo of this action
